# Question 1

In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Generating a 2 by 3 matrix containing elements from 1 to 6 

In [3]:
mat2 = np.array([[1,2,3],[4,5,6]])
print(mat2)

[[1 2 3]
 [4 5 6]]


In [4]:
mat2*2  # multiplying matrix by a scaler of 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [6]:
# Create a 3 by 3 identity matrix

In [9]:
mat3 = np.array([[[1,2,3],[4,5,6], [7,8,9]]])
print(mat3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# converting 1-D array (1-27) to 3 Dimenssion

In [58]:
array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

array3d = array1.reshape(1, 3, 9)

print(array3d)

[[[ 1  2  3  4  5  6  7  8  9]
  [10 11 12 13 14 15 16 17 18]
  [19 20 21 22 23 24 25 26 27]]]


In [ ]:
# Convert arry1 to a 3-D arry3D

In [56]:
arry3D = np.reshape(array1, (3, 9))
print(arry3D)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


In [20]:
array2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]]) # 2-D arrays Horizontally stack together

In [21]:
array2 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])   #  2-D arrays Vertically stack together
print(array2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [59]:
# creating equally spaced sequence with a gap of 5 ranging from 0 to 100

In [63]:
sequence = np.arange(0,101,5)
print(sequence)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


# Question 2

In [31]:
import pandas as pd  # import the pandas library

In [28]:
# 2a. DataFrame of student names

students = {'Names_of_students':['John', 'Maxwell', 'Joanna', 'Belinda', 'Hope']}
df = pd.DataFrame(students)
print(df)


  Names_of_students
0              John
1           Maxwell
2            Joanna
3           Belinda
4              Hope


In [ ]:
# 2b. GPL  Teams and the goals for previous five matches

In [35]:
teams = {'Team':['Hearts of Oak', 'Asante Kotoko', 'Ebusua Dwarfs', 'Sekondi Hassacas', 'Okwahu United', 'Tano Bofoakwa', 'BA United'], 'M1_Goals':[5,8,2,7,1,0,3], 'M2_Goals': [2,5,4,3,6,9,10], 'M3_Goals': [7,1,2,6,8,7,1], 'M4_Goals': [5,4,2,3,8,1,4], 'M5_Goals': [3,2,5,4,7,7,3]}
df = pd.DataFrame(teams)
print(df)

               Team  M1_Goals  M2_Goals  M3_Goals  M4_Goals  M5_Goals
0     Hearts of Oak         5         2         7         5         3
1     Asante Kotoko         8         5         1         4         2
2     Ebusua Dwarfs         2         4         2         2         5
3  Sekondi Hassacas         7         3         6         3         4
4     Okwahu United         1         6         8         8         7
5     Tano Bofoakwa         0         9         7         1         7
6         BA United         3        10         1         4         3


In [ ]:
# 2c. DataFrame for countries using a dictionary 

In [47]:
country = ['Benin', 'BurkinaFaso', 'Cape Verde', 'Gambia', 'Ghana', 'Guinea', 'Guinea-Bissau', 'Ivory Coast', 'Liberia', 'Mali', 'Mauretania', 'Niger', 'Nigeria', 'Senegal', 'Sierra Leone', 'Togo']
capital = ['Porto-Novo', 'Ouagadougou', 'Praia', 'Banjul', 'Accra', 'Conakry', 'Bissau', 'Yamoussoukro', 'Monrovia', 'Bamako', 'Nouakchott', 'Niamey', 'Abuja', 'Dakar', 'Freetown', 'Lome']
populationInMillion = [109, 187, 50, 20, 282, 124, 18, 237, 46, 180, 40, 1860, 150, 74, 76, 80]

In [50]:
dict_country = {'Country':country, 'Capital':capital, 'PopulationInMillion':populationInMillion}
country_pop = pd.DataFrame(dict_country)
country_pop

Country       Capital  PopulationInMillion
0           Benin    Porto-Novo                  109
1     BurkinaFaso   Ouagadougou                  187
2      Cape Verde         Praia                   50
3          Gambia        Banjul                   20
4           Ghana         Accra                  282
5          Guinea       Conakry                  124
6   Guinea-Bissau        Bissau                   18
7     Ivory Coast  Yamoussoukro                  237
8         Liberia      Monrovia                   46
9            Mali        Bamako                  180
10     Mauretania    Nouakchott                   40
11          Niger        Niamey                 1860
12        Nigeria         Abuja                  150
13        Senegal         Dakar                   74
14   Sierra Leone      Freetown                   76
15           Togo          Lome                   80

In [51]:
# 2Di. footbal dataFrame 
# Print the Team name along with Goals For (GF), Goals Against (GA) and Points (PTS).

In [94]:
teams = pd.DataFrame([['Hearts of Oak', 120, 35, 80], ['Asante Kotoko', 90,55,60], ['Ebusua Dwarfs', 90,60,60], ['Sekondi Hassacas', 80,43,55], ['Okwahu United', 78,39,53], ['Tano Boafoakwa', 70,50,49], ['BA United', 71,55,44]], columns = ['Team', 'GF', 'GA', 'PTS']) 
print(teams)

               Team   GF  GA  PTS
0     Hearts of Oak  120  35   80
1     Asante Kotoko   90  55   60
2     Ebusua Dwarfs   90  60   60
3  Sekondi Hassacas   80  43   55
4     Okwahu United   78  39   53
5    Tano Boafoakwa   70  50   49
6         BA United   71  55   44


In [ ]:
# 2dii.1, Teams that considered more than 30 goals

In [98]:
teams[['Team', 'GA']]

Team  GA
0     Hearts of Oak  35
1     Asante Kotoko  55
2     Ebusua Dwarfs  60
3  Sekondi Hassacas  43
4     Okwahu United  39
5    Tano Boafoakwa  50
6         BA United  55

In [ ]:
#  2dii.2, Teams that Scored less than 80 goals 

In [102]:
teams.iloc[4:7,0:2]

Team  GF
4   Okwahu United  78
5  Tano Boafoakwa  70
6       BA United  71

In [103]:
# 2dii.3, teams that had less than 60 points

In [125]:
teams.iloc[3:7,[0,3]]

Team  PTS
3  Sekondi Hassacas   55
4     Okwahu United   53
5    Tano Boafoakwa   49
6         BA United   44

# Question 3

In [126]:
# import CAR csv file to creat data frame
import pandas as pd

In [127]:
cars = pd.read_csv('E:/DigiCap/cars 2.csv')

In [ ]:
# finnding first and last five rows 

In [128]:
cars.head()  # this shows the first five rows of the data set

index  company          car_type  wheel-base  length engine-type  \
0      0    Honda       Convertible        88.6   168.8        dohc   
1      1    Honda       Convertible        88.6   168.8        dohc   
2      2    Honda  Four Wheel Drive        94.5   171.2        ohcv   
3      3  Hyundai         Salon car        99.8   176.6         ohc   
4      4  Hyundai         Salon car        99.4   176.6         ohc   

  num-of-cylinders  egine_capacity  average-km     price  Unnamed: 10  \
0             four             7.4    33.79614   87717.5          NaN   
1             four             7.4    33.79614  107250.0          NaN   
2              six            10.3    30.57746  107250.0          NaN   
3             four             6.8    38.62416   90675.0          NaN   
4             five             7.7    28.96812  113425.0          NaN   

   Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN

In [129]:
cars.tail()  # this shows the last five rows of the data set

index     company   car_type  wheel-base  length engine-type  \
56     81      Toyota  Salon car        97.3   171.7         ohc   
57     82      Toyota  Salon car        97.3   171.7         ohc   
58     86      Toyota  Salon car        97.3   171.7         ohc   
59     87  Mitsubishi  Salon car       104.3   188.8         ohc   
60     88  Mitsubishi      Wagon       104.3   188.8         ohc   

   num-of-cylinders  egine_capacity  average-km    price  Unnamed: 10  \
56             four             5.7    43.45218  51837.5          NaN   
57             four             3.5    59.54558  51967.5          NaN   
58             four             6.7    41.84284  64967.5          NaN   
59             four             7.6    37.01482  84110.0          NaN   
60             four             7.6    37.01482  87197.5          NaN   

    Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
56          NaN          NaN          NaN          NaN  
57          NaN          NaN          NaN          NaN  
58          NaN          NaN          NaN          NaN  
59          NaN          NaN          NaN          NaN  
60          NaN          NaN          NaN          NaN

In [ ]:
# 3b. Clean the dataset and update the CSV file

In [237]:
clean_cars = cars.drop(columns=['Unnamed: 14', 'Unnamed: 13', 'Unnamed: 12', 'Unnamed: 11', 'Unnamed: 10'])
clean_cars
clean_carsNA = clean_cars.dropna()
clean_carsNA

index     company          car_type  wheel-base  length engine-type  \
0       0       Honda       Convertible        88.6   168.8        dohc   
1       1       Honda       Convertible        88.6   168.8        dohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
7       9         Bmw         Salon car       101.2   176.8         ohc   
8      10         Bmw         Salon car       101.2   176.8         ohc   
9      11         Bmw         Salon car       101.2   176.8         ohc   
10     13         Bmw         Salon car       103.5   189.0         ohc   
11     14         Bmw         Salon car       103.5   193.8         ohc   
12     15         Bmw         Salon car       110.0   197.0         ohc   
13     16     Kantaka  Four Wheel Drive        88.4   141.1           l   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
27     36       Mazda  Four Wheel Drive        93.1   159.1         ohc   
28     37       Mazda  Four Wheel Drive        93.1   159.1         ohc   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
31     43       Mazda         Salon car       104.9   175.0         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
33     45      Toyota             Wagon       110.0   190.9         ohc   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
35     47      Toyota           hardtop       112.0   199.2        ohcv   
36     49  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
37     50  Mitsubishi  Four Wheel Drive        93.7   157.3         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
43     56      Nissan             Wagon        94.5   170.2         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
48     66       Honda  Four Wheel Drive        95.7   158.7         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
54     79       Honda             Wagon       104.5   187.8        dohc   
55     80      Toyota        

In [ ]:
# 3c.  Finding the most expensive car company name

In [239]:
clean_carsNA.sort_values(['price'], ascending=False).head() #Toyota is the most expensive car: 295100.0

index     company     car_type  wheel-base  length engine-type  \
35     47      Toyota      hardtop       112.0   199.2        ohcv   
11     14         Bmw    Salon car       103.5   193.8         ohc   
34     46      Toyota    Salon car       120.9   208.1        ohcv   
46     62  Mitsubishi  Convertible        89.5   168.9        ohcf   
12     15         Bmw    Salon car       110.0   197.0         ohc   

   num-of-cylinders  egine_capacity  average-km     price  
35            eight            12.3    22.53076  295100.0  
11              six            12.1    25.74944  268547.5  
34            eight            12.3    22.53076  266240.0  
46              six            13.8    27.35878  240682.0  
12              six            12.1    24.14010  239720.0

In [ ]:
# 3d. KANTAKA CAR DETAILS

In [168]:
df.loc[df['company'] == 'Kantaka']  # Printing All Kantaka Cars details

company          car_type  wheel-base  length engine-type  \
13  Kantaka  Four Wheel Drive        88.4   141.1           l   
14  Kantaka  Four Wheel Drive        94.5   155.9         ohc   
15  Kantaka         Salon car        94.5   158.8         ohc   
16  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
17  Kantaka  Four Wheel Drive        93.7   157.3         ohc   
18  Kantaka             Wagon        96.5   157.1         ohc   
19  Kantaka         Salon car        96.5   175.4         ohc   
20  Kantaka         Salon car        96.5   169.1         ohc   
21  Kantaka         Salon car        94.3   170.7         ohc   
22  Kantaka         Salon car        94.5   155.9         ohc   
23  Kantaka         Salon car        94.5   155.9         ohc   
24  Kantaka         Salon car       113.0   199.6        dohc   
25  Kantaka         Salon car       113.0   199.6        dohc   
26  Kantaka         Salon car       102.0   191.7        ohcv   

   num-of-cylinders  egine_capacity  average-km     price  
13            three             3.2    75.63898   33481.5  
14             four             4.7    61.15492   40917.5  
15             four             4.7    61.15492   42737.5  
16             four             4.5    49.88954   41450.5  
17             four             4.5    49.88954   40488.5  
18             four             5.1    48.28020   47417.5  
19             four             6.7    38.62416   84142.5  
20             four             6.7    40.23350   67242.5  
21             four             5.2    38.62416   44102.5  
22             four             4.7    61.15492       NaN  
23             four             4.7    61.15492       NaN  
24              six            11.7    24.14010  209625.0  
25              six            11.7    24.14010  231075.0  
26           twelve            17.5    20.92142  234000.0

In [ ]:
# 3e. Count total cars per company

In [240]:
print(clean_carsNA.company.value_counts())

Kantaka       12
Honda         10
Toyota         8
Mitsubishi     8
Bmw            6
Nissan         5
Mazda          5
Hyundai        4
Name: company, dtype: int64


In [ ]:
# 3f. company with highist car price

In [241]:
companyCarPrice = clean_carsNA.groupby('company')
companyCarPrice[['company', 'price']].max()

company     price
company                         
Bmw                Bmw  268547.5
Honda            Honda  107250.0
Hyundai        Hyundai  122980.0
Kantaka        Kantaka  234000.0
Mazda            Mazda  119236.0
Mitsubishi  Mitsubishi  240682.0
Nissan          Nissan   87743.5
Toyota          Toyota  295100.0

In [242]:
#3g. average mileage of each car making company

In [243]:
companyAvMile = clean_carsNA.groupby('company')
companyAvMile[['company', 'average-km']].mean()

average-km
company               
Bmw          30.577460
Honda        42.164708
Hyundai      32.186800
Kantaka      44.390962
Mazda        45.061520
Mitsubishi   39.831165
Nissan       50.533276
Toyota       40.032333

In [ ]:
# 3h Sort all cars by Price column

In [244]:
clean_carsNA.sort_values(by=['price'], ascending=False)

index     company          car_type  wheel-base  length engine-type  \
35     47      Toyota           hardtop       112.0   199.2        ohcv   
11     14         Bmw         Salon car       103.5   193.8         ohc   
34     46      Toyota         Salon car       120.9   208.1        ohcv   
46     62  Mitsubishi       Convertible        89.5   168.9        ohcf   
12     15         Bmw         Salon car       110.0   197.0         ohc   
26     35     Kantaka         Salon car       102.0   191.7        ohcv   
25     34     Kantaka         Salon car       113.0   199.6        dohc   
45     61  Mitsubishi       Convertible        89.5   168.9        ohcf   
24     33     Kantaka         Salon car       113.0   199.6        dohc   
10     13         Bmw         Salon car       103.5   189.0         ohc   
33     45      Toyota             Wagon       110.0   190.9         ohc   
32     44      Toyota         Salon car       110.0   190.9         ohc   
9      11         Bmw         Salon car       101.2   176.8         ohc   
6       6     Hyundai             Wagon       105.8   192.7         ohc   
31     43       Mazda         Salon car       104.9   175.0         ohc   
4       4     Hyundai         Salon car        99.4   176.6         ohc   
8      10         Bmw         Salon car       101.2   176.8         ohc   
2       2       Honda  Four Wheel Drive        94.5   171.2        ohcv   
1       1       Honda       Convertible        88.6   168.8        dohc   
7       9         Bmw         Salon car       101.2   176.8         ohc   
54     79       Honda             Wagon       104.5   187.8        dohc   
5       5     Hyundai         Salon car        99.8   177.3         ohc   
3       3     Hyundai         Salon car        99.8   176.6         ohc   
44     57      Nissan         Salon car       100.4   184.6        ohcv   
0       0       Honda       Convertible        88.6   168.8        dohc   
60     88  Mitsubishi             Wagon       104.3   188.8         ohc   
19     28     Kantaka         Salon car        96.5   175.4         ohc   
59     87  Mitsubishi         Salon car       104.3   188.8         ohc   
30     39       Mazda  Four Wheel Drive        95.3   169.0       rotor   
20     29     Kantaka         Salon car        96.5   169.1         ohc   
58     86      Toyota         Salon car        97.3   171.7         ohc   
53     71       Honda             Wagon        95.7   169.7         ohc   
39     52  Mitsubishi         Salon car        96.3   172.4         ohc   
57     82      Toyota         Salon car        97.3   171.7         ohc   
56     81      Toyota         Salon car        97.3   171.7         ohc   
52     70       Honda             Wagon        95.7   169.7         ohc   
55     80      Toyota         Salon car        97.3   171.7         ohc   
43     56      Nissan             Wagon        94.5   170.2         ohc   
18     27     Kantaka             Wagon        96.5   157.1         ohc   
40     53      Nissan         Salon car        94.5   165.3         ohc   
38     51  Mitsubishi         Salon car        96.3   172.4         ohc   
51     69       Honda             Wagon        95.7   169.7         ohc   
42     55      Nissan         Salon car        94.5   165.3         ohc   
29     38       Mazda  Four Wheel Drive        93.1   159.1         ohc   
21     30     Kantaka         Salon car        94.3   170.7         ohc   
41     54      Nissan         Salon car        94.5   165.3         ohc   
15     18     Kantaka         Salon car        94.5   158.8         ohc   
50     68       Honda  Four Wheel Drive        95.7   158.7         ohc   
16     19     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
49     67       Honda  Four Wheel Drive        95.7   158.7         ohc   
14     17     Kantaka  Four Wheel Drive        94.5   155.9         ohc   
17     20     Kantaka  Four Wheel Drive        93.7   157.3         ohc   
37     50  Mitsubishi  Four W

In [ ]:
# 3h. Concatenate two data frames Ghana cars and Japanes Cars

In [247]:
GhanaCars = {'Company': ['KANTAKA', 'VW', 'BMW', 'NEOPLAN'], 'Price': [23845,171995,135925,71400]}

JapaneseCars = {'Company': ['Toyota', 'Honda', 'Nissan', 'Mitsubishi'], 'Price':[29995,23600,61500,58900]}
GCar = pd.DataFrame.from_dict(GhanaCars)
JCar = pd.DataFrame(JapaneseCars)

df_cars = pd.concat([GCar,JCar], keys=['Ghana','Japan'])
df_cars

Company   Price
Ghana 0     KANTAKA   23845
      1          VW  171995
      2         BMW  135925
      3     NEOPLAN   71400
Japan 0      Toyota   29995
      1       Honda   23600
      2      Nissan   61500
      3  Mitsubishi   58900